sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '4.4.2'
before_install:
  - npm i -g npm@^2.0.0
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
